version: 2
jobs:
  build:
    working_directory: /go/src/github.com/cloudconsole/cloudspider

    docker:
      - image: golang:1.8.0

    steps:
      - checkout

      - run:
          name: Run UI unit tests
          command: go test -v -race ./ui

      - run:
          name: Build service
          command: go build

      - run:
          name: Start service
          command: ./cloudspider ui start
          background: true

      - run:
          name: Validate service is working
          command: curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:5000/
