version: 2
jobs:
  build:
    working_directory: /go/src/github.com/cloudconsole/cloudspider

    docker:
      - image: golang:1.8.
        cmd: ["/bin/bash"]

    steps:
      - checkout

      - run:
          name: Install system dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_7.x | bash -
            apt-get install -y nodejs
            wget -qO- https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz | tar -zxf -
            mv linux-amd64/glide /usr/bin/
            rm -rf linux-amd64/

      - run:
            name: Install backend dependencies
            command: glide install

      - run:
          name: Install frontend dependencies
          command: npm install

      - run:
          name: Run UI unit tests
          command: go test -v -race ./ui

      - run:
          name: Build frontend
          command: npm run build

      - run:
          name: Build backend
          command: go build

      - run:
          name: Start service
          command: |
            cp conf/sample_config.yaml config.yaml
            ./cloudspider ui start
          background: true

      - run:
          name: Validate service is working
          command: curl --retry 3 --retry-delay 1 http://localhost:5000/
