---
appname: Cloud Spider

# The address:port of the interface to bind to:
bindaddr: 127.0.0.1:5000

# Supported Cloud Providers
cloudservices:
  aws: False
  ultradns: False
  dnsmadeeasy: False
  akamai: False

# Datacenters
regions:
  - us-east-1
  - us-west-1
  - us-west-2
  - eu-west-1

# Crawler configuration
crawler:
  pagesize: 100

# Database configuration
mongodb:
  uri: mongodb://localhost:27017/
  dbname: cloudspider

# log config
log:
  file: /tmp/cloudspider.log
  # valid level : panic, fatal, error, warn, info, debug
  level: error

ultradns:
  username: username
  password: xyzasdfgh

akamai:
  baseurl: https://akamai_base_url
  clienttoken: xxxxxx
  clientsecret: xxxxxxx
  accesstoken: xxxxxxxx
  maxbody: 131072
